FROM serversideup/php:8.4-fpm-nginx

# Switch to root to install extensions
USER root

# Install missing PHP extensions for Laravel + Filament + Spatie Media Library
RUN install-php-extensions intl exif gd imagick

# Switch back to www-data user
USER www-data
